name: Ci Cd

on:
    push:
        branches: [main]

jobs:
    Test:
        runs-on: windows-latest
        steps:
            - name: Repasitoryni yuklash
              uses: actions/checkout@v4

            - name: node_modules
              run: npm install

            - name: Build qilish
              run: npm run build